### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by omidshy** [mackerell-lab/drude_electrostatic_dnn#1]
Hi,
how can the trained models be used to predict electrostatic parameters for new molecules?

**Comment by anmolecule** [comment]
A feature vector needs to be generated for new molecule for obtaining the electrostatic parameters. We are in the process of deploying the model to get electrostatic parameters along with bonded and van der Waals parameters. The optimization of latter two is in progress. Please wait...
Thanks for your interest.
